spring:
  profiles:
    active: dev # defualt
    group:
      dev:
        - common
        - dev

---
spring:
  config:
    activate:
      on-profile: "common"

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  logging:
    level:
      ROOT: INFO
      org.springframework.orm.jpa: DEBUG
      org.springframework.transaction: DEBUG
      org.hibernate.type.descriptor.sql: trace

---

spring:
  config:
    activate:
      on-profile: dev

security:
  jwt:
    token:
      secret-key: atdd-secret-key
      expire-length: 3600000

github:
  base-url: https://github.com/
  client:
    id: client-id
    secret: github-client-secret